const db = require("./database");
const ProductModel = require("./product.model");

const products = [
  {
    name: "Silk Evening Dress",
    description: "A stunning floor-length evening dress crafted from pure silk. Features a delicate drape and a flattering silhouette perfect for formal occasions.",
    category: "For Her",
    price: 899,
    image: "https://images.unsplash.com/photo-1678723357379-d87f2a0ec8ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=1083", "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&q=80&w=1083"],
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Designer Wool Coat",
    description: "Expertly tailored from premium wool blend. This coat combines warmth with timeless elegance, featuring a structured collar and gold-tone buttons.",
    category: "For Her",
    price: 1299,
    image: "https://images.unsplash.com/photo-1762605135012-56a59a059e60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Premium Blazer",
    description: "A sharp, modern blazer for the contemporary gentleman. Italian cut, breathable fabric, and impeccable stitching details.",
    category: "For Him",
    price: 799,
    image: "https://images.unsplash.com/photo-1515736076039-a3ca66043b27?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["48", "50", "52", "54"],
  },
  {
    name: "Luxury Heels",
    description: "Handcrafted Italian leather heels. Designed for both comfort and style, these stilettos add a touch of glamour to any outfit.",
    category: "Accessories",
    price: 549,
    image: "https://images.unsplash.com/photo-1760331339913-da9637154477?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    name: "Leather Handbag",
    description: "Genuine full-grain leather handbag with gold hardware accents. Spacious interior with multiple compartments for organization.",
    category: "Accessories",
    price: 1199,
    image: "https://images.unsplash.com/photo-1682317056294-1970c953cfd7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Gold Necklace",
    description: "18k Gold plated statement necklace. A bold piece that elevates even the simplest attire.",
    category: "Accessories",
    price: 2499,
    image: "https://images.unsplash.com/photo-1762505464426-7467c051ea76?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Silk Scarf",
    description: "100% Mulberry silk scarf featuring a custom Vestimenta print. Soft, lightweight, and versatile.",
    category: "Accessories",
    price: 349,
    image: "https://images.unsplash.com/photo-1761660450845-6c3aa8aaf43f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Designer Belt",
    description: "Reversible leather belt with the iconic V-buckle in brushed gold. A wardrobe staple.",
    category: "Accessories",
    price: 299,
    image: "https://images.unsplash.com/photo-1664286074240-d7059e004dff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["85", "90", "95", "100"],
  },
  {
    name: "Cashmere Sweater",
    description: "Ultra-soft cashmere sweater with a classic crew neck. Perfect for layering or wearing alone on crisp autumn days.",
    category: "For Her",
    price: 649,
    image: "https://images.unsplash.com/photo-1603906650843-b58e94d9df4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Cocktail Dress",
    description: "Elegant cocktail dress with delicate lace details. Features a fitted bodice and flowing skirt for a sophisticated look.",
    category: "For Her",
    price: 749,
    image: "https://images.unsplash.com/photo-1622079400125-5b6679552976?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Leather Moto Jacket",
    description: "Classic motorcycle-style leather jacket with asymmetric zip closure. Timeless design with modern edge.",
    category: "For Her",
    price: 1099,
    image: "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Tailored Suit",
    description: "Three-piece suit in premium Italian wool. Includes jacket, vest, and trousers for a complete formal ensemble.",
    category: "For Him",
    price: 1899,
    image: "https://images.unsplash.com/photo-1618886614638-80e3c103d31a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    name: "Floral Summer Dress",
    description: "Lightweight summer dress with vibrant floral print. Breathable fabric perfect for warm weather.",
    category: "For Her",
    price: 459,
    image: "https://images.unsplash.com/photo-1613966570650-add3cf83aa83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Oxford Dress Shoes",
    description: "Classic oxford shoes in premium calfskin leather. Goodyear welted construction for lasting quality.",
    category: "For Him",
    price: 599,
    image: "https://images.unsplash.com/photo-1614253429340-98120bd6d753?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    name: "Luxury Watch",
    description: "Swiss-made automatic watch with sapphire crystal and stainless steel case. A timepiece that transcends trends.",
    category: "Accessories",
    price: 3499,
    image: "https://images.unsplash.com/photo-1702865053958-71ec751c4118?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Designer Sunglasses",
    description: "Premium acetate sunglasses with polarized lenses. UV protection meets high fashion.",
    category: "Accessories",
    price: 449,
    image: "https://images.unsplash.com/photo-1663585703603-9be01a72a62a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Classic Trench Coat",
    description: "Double-breasted trench coat in water-resistant gabardine. A timeless essential for any wardrobe.",
    category: "For Her",
    price: 999,
    image: "https://images.unsplash.com/photo-1633821879282-0c4e91f96232?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Premium Denim Jeans",
    description: "Selvedge denim jeans with perfect fit and fade. Japanese fabric, Italian construction.",
    category: "For Him",
    price: 399,
    image: "https://images.unsplash.com/photo-1658910453954-6ca847bb7470?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    name: "Silk Blouse",
    description: "Luxurious silk blouse with delicate mother-of-pearl buttons. Effortlessly elegant for office or evening.",
    category: "For Her",
    price: 529,
    image: "https://images.unsplash.com/photo-1761117228880-df2425bd70da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "White Leather Sneakers",
    description: "Minimalist white leather sneakers with premium Italian craftsmanship. Comfort meets contemporary style.",
    category: "Accessories",
    price: 379,
    image: "https://images.unsplash.com/photo-1651371409956-20e79c06a8bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
  },
  {
    name: "Merino Wool Sweater",
    description: "Fine merino wool sweater with ribbed detailing. Lightweight warmth for transitional weather.",
    category: "For Him",
    price: 449,
    image: "https://images.unsplash.com/photo-1588271968087-4c51abe05afc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Pleated Midi Skirt",
    description: "Flowing pleated skirt in lightweight fabric. Versatile piece that moves beautifully with every step.",
    category: "For Her",
    price: 389,
    image: "https://images.unsplash.com/photo-1533659828870-95ee305cee3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Women's Power Blazer",
    description: "Structured blazer with peak lapels and padded shoulders. Commanding presence for the modern professional.",
    category: "For Her",
    price: 849,
    image: "https://images.unsplash.com/photo-1521510895919-46920266ddb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Leather Loafers",
    description: "Hand-stitched penny loafers in premium leather. Classic style with exceptional comfort.",
    category: "For Him",
    price: 529,
    image: "https://images.unsplash.com/photo-1673675270277-95e45ee5d2e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    name: "Crossbody Bag",
    description: "Compact crossbody bag in supple leather. Perfect size for essentials with adjustable strap.",
    category: "Accessories",
    price: 699,
    image: "https://images.unsplash.com/photo-1718622795525-2295971921ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Wool Fedora",
    description: "Classic fedora hat in 100% wool felt. Adds sophistication to any outfit.",
    category: "Accessories",
    price: 249,
    image: "https://images.unsplash.com/photo-1729100698067-10028f6169d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L"],
  },
  {
    name: "Pearl Drop Earrings",
    description: "Freshwater pearl earrings set in 14k gold. Timeless elegance for any occasion.",
    category: "Accessories",
    price: 899,
    image: "https://images.unsplash.com/photo-1704957205218-d436eac4c607?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Turtleneck Sweater",
    description: "Sleek turtleneck in fine-gauge knit. A versatile layering piece for colder months.",
    category: "For Her",
    price: 379,
    image: "https://images.unsplash.com/photo-1608739872077-21ddc15dc152?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Suede Ankle Boots",
    description: "Elegant ankle boots in soft suede with block heel. Comfortable height perfect for all-day wear.",
    category: "Accessories",
    price: 649,
    image: "https://images.unsplash.com/photo-1571489555750-c932b569ef5d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    name: "Knit Cardigan",
    description: "Oversized cardigan in chunky knit. Cozy comfort with modern silhouette.",
    category: "For Her",
    price: 429,
    image: "https://images.unsplash.com/photo-1633438584121-ec60a7d453d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Flowing Maxi Dress",
    description: "Floor-length maxi dress with elegant draping. Perfect for summer evenings and special occasions.",
    category: "For Her",
    price: 599,
    image: "https://images.unsplash.com/photo-1692220438327-fd668e8a7bbb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Chino Trousers",
    description: "Tailored chino pants in premium cotton twill. Smart-casual essential with perfect fit.",
    category: "For Him",
    price: 329,
    image: "https://images.unsplash.com/photo-1584865288642-42078afe6942?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["30", "32", "34", "36", "38", "40"],
  },
  {
    name: "Gold Chain Bracelet",
    description: "Bold chain-link bracelet in 18k gold vermeil. Makes a statement worn alone or stacked.",
    category: "Accessories",
    price: 729,
    image: "https://images.unsplash.com/photo-1744472457504-f99a96ecbd3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Classic Polo Shirt",
    description: "Pique cotton polo in timeless design. Elevated casual wear for the discerning gentleman.",
    category: "For Him",
    price: 259,
    image: "https://images.unsplash.com/photo-1625910513413-c23b8bb81cba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Evening Clutch",
    description: "Sleek clutch bag with crystal clasp. Compact elegance for formal events.",
    category: "Accessories",
    price: 549,
    image: "https://images.unsplash.com/photo-1598552105309-9243044d2002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Formal Dress Shirt",
    description: "Crisp white dress shirt in Egyptian cotton. French cuffs and mother-of-pearl buttons.",
    category: "For Him",
    price: 349,
    image: "https://images.unsplash.com/photo-1602810316693-3667c854239a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    name: "Wedge Sandals",
    description: "Espadrille wedge sandals with ankle tie. Summer elegance with comfortable lift.",
    category: "Accessories",
    price: 429,
    image: "https://images.unsplash.com/photo-1603290939650-b553549a5739?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    name: "Tailored Vest",
    description: "Five-button vest in wool blend. Perfect for layering under suits or wearing solo.",
    category: "For Him",
    price: 399,
    image: "https://images.unsplash.com/photo-1754577060025-9b0831bdc554?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["46", "48", "50", "52", "54"],
  },
  {
    name: "Satin Midi Skirt",
    description: "Bias-cut midi skirt in luxurious satin. Elegant movement and lustrous finish.",
    category: "For Her",
    price: 479,
    image: "https://images.unsplash.com/photo-1556747439-3b96858b9d8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Leather Messenger Bag",
    description: "Vintage-style messenger bag in full-grain leather. Spacious compartments for work essentials.",
    category: "Accessories",
    price: 899,
    image: "https://images.unsplash.com/photo-1528976915572-6a0cf746802e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Silk Tie",
    description: "Hand-rolled silk tie in sophisticated pattern. The perfect finishing touch to formal attire.",
    category: "Accessories",
    price: 159,
    image: "https://images.unsplash.com/photo-1578652681036-beb0d4a25518?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Leather Ballet Flats",
    description: "Classic ballet flats in buttery soft leather. Timeless comfort for everyday elegance.",
    category: "Accessories",
    price: 399,
    image: "https://images.unsplash.com/photo-1676300816371-e02ca73af33c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    name: "Down Parka",
    description: "Insulated down parka with fur-trimmed hood. Maximum warmth without bulk.",
    category: "For Him",
    price: 1199,
    image: "https://images.unsplash.com/photo-1571867424485-369464ed33cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Leather Backpack",
    description: "Modern backpack in premium leather. Laptop compartment and organizational pockets.",
    category: "Accessories",
    price: 849,
    image: "https://images.unsplash.com/photo-1549943872-f7ff0b2b51be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Cashmere Beanie",
    description: "Luxurious cashmere beanie with ribbed design. Soft warmth for winter days.",
    category: "Accessories",
    price: 189,
    image: "https://images.unsplash.com/photo-1633964124833-f4f3928c55bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Wrap Dress",
    description: "Flattering wrap dress in jersey fabric. Adjustable tie waist for perfect fit.",
    category: "For Her",
    price: 499,
    image: "https://images.unsplash.com/photo-1759992878336-a5dd342ea245?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Bomber Jacket",
    description: "Modern bomber in technical fabric with ribbed cuffs. Contemporary classic for casual wear.",
    category: "For Him",
    price: 599,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Diamond Pendant",
    description: "Solitaire diamond pendant on delicate chain. Timeless sparkle for everyday wear.",
    category: "Accessories",
    price: 1899,
    image: "https://images.unsplash.com/photo-1763256614647-14abbc578252?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Suede Boat Shoes",
    description: "Handcrafted boat shoes in premium suede. Comfortable and stylish for casual occasions.",
    category: "For Him",
    price: 429,
    image: "https://images.unsplash.com/photo-1715764783691-da317960ba09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    name: "Canvas Tote Bag",
    description: "Spacious canvas tote with leather handles. Practical elegance for everyday use.",
    category: "Accessories",
    price: 299,
    image: "https://images.unsplash.com/photo-1574365569389-a10d488ca3fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Tailored Jumpsuit",
    description: "One-piece jumpsuit with structured bodice. Effortless sophistication in a single garment.",
    category: "For Her",
    price: 749,
    image: "https://images.unsplash.com/photo-1582757794585-ddff6bb050c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Silver Cufflinks",
    description: "Classic cufflinks in sterling silver with engraved detail. Refined accent for dress shirts.",
    category: "Accessories",
    price: 349,
    image: "https://images.unsplash.com/photo-1643393669090-5b866afd2d32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Navy Peacoat",
    description: "Double-breasted peacoat in wool melton. Naval-inspired classic for winter warmth.",
    category: "For Him",
    price: 899,
    image: "https://images.unsplash.com/photo-1626872640220-e5f4454198b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Statement Rings Set",
    description: "Set of three stackable rings in mixed metals. Modern jewelry for everyday glamour.",
    category: "Accessories",
    price: 599,
    image: "https://images.unsplash.com/photo-1649118499283-1c7ff168a6d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["6", "7", "8", "9"],
  },
  {
    name: "Linen Shirt",
    description: "Breathable linen shirt with relaxed fit. Summer essential in natural fabric.",
    category: "For Him",
    price: 299,
    image: "https://images.unsplash.com/photo-1591357037205-166318b51afd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Espadrille Wedges",
    description: "Jute wedge espadrilles with canvas upper. Mediterranean style meets comfort.",
    category: "Accessories",
    price: 329,
    image: "https://images.unsplash.com/photo-1664819056581-13be5d816564?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    name: "Leather Wallet",
    description: "Bifold wallet in vegetable-tanned leather. Slim profile with card slots and bill compartment.",
    category: "Accessories",
    price: 249,
    image: "https://images.unsplash.com/photo-1676276549701-668493cff405?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Silk Kimono",
    description: "Flowing kimono robe in printed silk. Luxurious loungewear with artistic flair.",
    category: "For Her",
    price: 629,
    image: "https://images.unsplash.com/photo-1663044023021-89c818cf9f2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Performance Running Shoes",
    description: "Technical running shoes with cushioned sole. High-performance comfort for active lifestyle.",
    category: "Accessories",
    price: 349,
    image: "https://images.unsplash.com/photo-1597892657493-6847b9640bac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["37", "38", "39", "40", "41", "42", "43", "44", "45"],
  },
  {
    name: "Leather Pencil Skirt",
    description: "Sleek pencil skirt in supple leather. Modern edge with sophisticated silhouette.",
    category: "For Her",
    price: 699,
    image: "https://images.unsplash.com/photo-1761746395517-17db0c59d495?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Hooded Sweatshirt",
    description: "Premium cotton hoodie with brushed interior. Elevated comfort for casual days.",
    category: "For Him",
    price: 299,
    image: "https://images.unsplash.com/photo-1625752437468-a609f6139b11?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Leather Driving Gloves",
    description: "Supple leather gloves with perforated details. Classic accessory for the discerning driver.",
    category: "Accessories",
    price: 279,
    image: "https://images.unsplash.com/photo-1643650374762-196c86358df3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L"],
  },
  {
    name: "Wool Winter Scarf",
    description: "Extra-long scarf in soft merino wool. Wrap yourself in luxurious warmth.",
    category: "Accessories",
    price: 229,
    image: "https://images.unsplash.com/photo-1669626495508-58acf2311688?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Canvas Duffel Bag",
    description: "Weekender duffel in waxed canvas with leather trim. Adventure-ready style.",
    category: "Accessories",
    price: 599,
    image: "https://images.unsplash.com/photo-1448582649076-3981753123b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Athletic Sport Jacket",
    description: "Technical sport jacket with moisture-wicking fabric. Performance meets style.",
    category: "For Him",
    price: 449,
    image: "https://images.unsplash.com/photo-1715608720717-ac3d1b638e44?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Strappy Leather Sandals",
    description: "Minimalist leather sandals with ankle strap. Sophisticated simplicity for summer.",
    category: "Accessories",
    price: 389,
    image: "https://images.unsplash.com/photo-1613662632164-7f2b081a5b46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    name: "Ribbed Crop Top",
    description: "Fitted crop top in ribbed cotton. Versatile layering piece with modern cut.",
    category: "For Her",
    price: 159,
    image: "https://images.unsplash.com/photo-1548389995-fbd3151a501f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Utility Cargo Pants",
    description: "Modern cargo pants with multiple pockets. Function meets fashion in contemporary silhouette.",
    category: "For Him",
    price: 379,
    image: "https://images.unsplash.com/photo-1584302052177-2e90841dad6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    name: "Chelsea Leather Boots",
    description: "Classic chelsea boots in premium leather. Timeless style with elastic side panels.",
    category: "For Him",
    price: 749,
    image: "https://images.unsplash.com/photo-1599012307605-23a0ebe4d321?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    name: "Vintage Brooch",
    description: "Art deco-inspired brooch with crystal details. Heirloom-quality statement piece.",
    category: "Accessories",
    price: 649,
    image: "https://images.unsplash.com/photo-1610454958462-571795784d98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Technical Raincoat",
    description: "Water-resistant raincoat with sealed seams. Weather protection without compromise.",
    category: "For Her",
    price: 799,
    image: "https://images.unsplash.com/photo-1504616267454-5460d659c9be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Cotton Tank Top",
    description: "Essential tank top in organic cotton. Perfect basic for layering or solo wear.",
    category: "For Her",
    price: 89,
    image: "https://images.unsplash.com/photo-1601838165307-6a5a08616f97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Jogger Track Pants",
    description: "Tapered track pants in technical fabric. Athleisure comfort with refined details.",
    category: "For Him",
    price: 249,
    image: "https://images.unsplash.com/photo-1719473466836-ff9f5ebe0e1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Executive Briefcase",
    description: "Structured briefcase in full-grain leather. Professional elegance for business essentials.",
    category: "Accessories",
    price: 1299,
    image: "https://images.unsplash.com/photo-1603219527847-24c87f552a77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Packable Windbreaker",
    description: "Lightweight windbreaker that packs into its own pocket. Travel-friendly weather protection.",
    category: "For Him",
    price: 329,
    image: "https://images.unsplash.com/photo-1551794840-8ae3b9c181f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Gold Anklet",
    description: "Delicate chain anklet in 14k gold. Subtle sparkle for summer style.",
    category: "Accessories",
    price: 399,
    image: "https://images.unsplash.com/photo-1651395835317-d2868e8ebcac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Varsity Jacket",
    description: "Classic varsity jacket with wool body and leather sleeves. American collegiate style.",
    category: "For Him",
    price: 649,
    image: "https://images.unsplash.com/photo-1682354163828-d1d56c380431?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Velvet Slippers",
    description: "Luxurious velvet slippers with embroidered detail. Refined comfort for at-home elegance.",
    category: "Accessories",
    price: 349,
    image: "https://images.unsplash.com/photo-1712193040438-1bcc495e1a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
  },
  {
    name: "Silk Bow Tie",
    description: "Pre-tied bow tie in fine silk. Classic formal accessory with adjustable neck band.",
    category: "Accessories",
    price: 129,
    image: "https://images.unsplash.com/photo-1610599905000-a8093ff22a55?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Quilted Shoulder Bag",
    description: "Classic quilted bag with chain strap. Timeless design in luxurious leather.",
    category: "Accessories",
    price: 1499,
    image: "https://images.unsplash.com/photo-1523779105320-d1cd346ff52b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Satin Corset Top",
    description: "Structured corset top in lustrous satin. Statement piece for evening glamour.",
    category: "For Her",
    price: 529,
    image: "https://images.unsplash.com/photo-1717616870208-a805ea578555?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Wide Leg Trousers",
    description: "Flowing wide-leg pants in crepe fabric. Sophisticated comfort with elegant drape.",
    category: "For Her",
    price: 449,
    image: "https://images.unsplash.com/photo-1695231081377-2765f838043d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Biker Leather Jacket",
    description: "Heavy-duty leather motorcycle jacket with multiple zippers. Rock-and-roll edge.",
    category: "For Him",
    price: 1399,
    image: "https://images.unsplash.com/photo-1654720498638-46c8d93bc32d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Suede Mules",
    description: "Backless mules in soft suede. Effortless slip-on style for modern living.",
    category: "Accessories",
    price: 429,
    image: "https://images.unsplash.com/photo-1563891982416-bf79e893fb44?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    name: "Silk Pocket Square",
    description: "Hand-rolled pocket square in printed silk. Refined detail for suit jackets.",
    category: "Accessories",
    price: 99,
    image: "https://images.unsplash.com/photo-1637531747440-53fde44ee60f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Crystal Tiara",
    description: "Delicate tiara with Swarovski crystals. Bridal elegance or special occasion sparkle.",
    category: "Accessories",
    price: 899,
    image: "https://images.unsplash.com/photo-1595321398361-a96bfd6a5d7f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Classic Denim Jacket",
    description: "Vintage-wash denim jacket with classic fit. Timeless casual staple.",
    category: "For Her",
    price: 349,
    image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Beaded Evening Clutch",
    description: "Hand-beaded clutch with satin lining. Artisanal craftsmanship for formal occasions.",
    category: "Accessories",
    price: 799,
    image: "https://images.unsplash.com/photo-1742626181959-f6442aea029b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Oxford Button-Down Shirt",
    description: "Classic oxford shirt in premium cotton. Wardrobe essential with button-down collar.",
    category: "For Him",
    price: 229,
    image: "https://images.unsplash.com/photo-1651087319658-a1923f85551f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Platform Heels",
    description: "Sky-high platform heels with ankle strap. Drama and stability in one statement shoe.",
    category: "Accessories",
    price: 599,
    image: "https://images.unsplash.com/photo-1535038872957-c20dea0c6f26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    name: "Gold Money Clip",
    description: "Slim money clip in brushed gold finish. Minimalist sophistication for cash and cards.",
    category: "Accessories",
    price: 299,
    image: "https://images.unsplash.com/photo-1758813095125-59d311656320?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Wool Beret",
    description: "French-style beret in soft wool. Parisian chic for everyday wear.",
    category: "Accessories",
    price: 159,
    image: "https://images.unsplash.com/photo-1700853786173-8c6759a7a14e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Faux Fur Coat",
    description: "Luxurious faux fur coat with satin lining. Glamorous warmth without compromise.",
    category: "For Her",
    price: 1099,
    image: "https://images.unsplash.com/photo-1674471361345-e787eaf7dd8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Premium Messenger Bag",
    description: "Urban messenger bag in ballistic nylon with leather accents. Durability meets design.",
    category: "Accessories",
    price: 699,
    image: "https://images.unsplash.com/photo-1637762647056-998cc4715de7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Formal Suspenders",
    description: "Classic Y-back suspenders with leather tabs. Traditional elegance for formal wear.",
    category: "Accessories",
    price: 179,
    image: "https://images.unsplash.com/photo-1503327151497-be3b97ef0d42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Embellished Hair Clip",
    description: "Decorative hair clip with pearl and crystal details. Functional accessory meets jewelry.",
    category: "Accessories",
    price: 149,
    image: "https://images.unsplash.com/photo-1593243878152-e60ce779e43d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Printed Floral Dress",
    description: "Romantic floral dress with ruffled hem. Garden party perfection in flowing fabric.",
    category: "For Her",
    price: 529,
    image: "https://images.unsplash.com/photo-1511130558090-00af810c21b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Leather Hobo Bag",
    description: "Slouchy hobo bag in distressed leather. Bohemian style with spacious interior.",
    category: "Accessories",
    price: 849,
    image: "https://images.unsplash.com/photo-1758499537503-315ca95c010b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Tailored Dress Shorts",
    description: "Smart shorts in tropical wool. Summer sophistication for warm-weather dressing.",
    category: "For Him",
    price: 299,
    image: "https://images.unsplash.com/photo-1661839750839-af5c5ed2a7b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    name: "Heavy Chain Necklace",
    description: "Bold chain necklace in gold vermeil. Statement jewelry for confident style.",
    category: "Accessories",
    price: 949,
    image: "https://images.unsplash.com/photo-1685970731194-e27b477e87ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Embroidered Tunic",
    description: "Flowing tunic with intricate embroidery. Artisanal details on effortless silhouette.",
    category: "For Her",
    price: 449,
    image: "https://images.unsplash.com/photo-1719535219127-f6477ddd8bf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    name: "Sports Gym Bag",
    description: "Versatile gym bag with shoe compartment and water bottle holder. Fitness meets function.",
    category: "Accessories",
    price: 199,
    image: "https://images.unsplash.com/photo-1535879335191-618713ec3e3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["One Size"],
  },
  {
    name: "Henley Long Sleeve",
    description: "Classic henley in soft cotton blend. Casual comfort with button placket detail.",
    category: "For Him",
    price: 179,
    image: "https://images.unsplash.com/photo-1595349238726-59fcb6b6be26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Charm Bracelet",
    description: "Sterling silver bracelet with interchangeable charms. Personalize your story.",
    category: "Accessories",
    price: 499,
    image: "https://images.unsplash.com/photo-1647638162212-51180c35deae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Jersey Romper",
    description: "One-piece romper in soft jersey. Playful ease for casual summer days.",
    category: "For Her",
    price: 299,
    image: "https://images.unsplash.com/photo-1609306515474-41187c86b38b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: false,
    sizes: ["XS", "S", "M", "L"],
  },
  {
    name: "Structured Satchel",
    description: "Vintage-inspired satchel with buckle closure. Timeless design in quality leather.",
    category: "Accessories",
    price: 749,
    image: "https://images.unsplash.com/photo-1758499537503-315ca95c010b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["One Size"],
  },
  {
    name: "Quilted Puffer Jacket",
    description: "Lightweight puffer with down insulation. Modern warmth in sleek silhouette.",
    category: "For Him",
    price: 699,
    image: "https://images.unsplash.com/photo-1706765779494-2705542ebe74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isNew: true,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
];

const schemaQuery = `
  DROP TABLE IF EXISTS products;

  CREATE TABLE products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      category VARCHAR(100),
      price NUMERIC(10, 2) NOT NULL,
      image TEXT,
      images JSONB DEFAULT '[]',
      isNew BOOLEAN DEFAULT false,
      sizes JSONB DEFAULT '[]', 
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );
`;

async function runSeed() {
  console.log("🌱 Seeding Products Database...");

  try {
    await db.query(schemaQuery);
    console.log("  - 'products' table created successfully");

    for (const product of products) {
      const createdProduct = await ProductModel.create(product);
      console.log(`    ✓ Created: [${createdProduct.id}] ${createdProduct.name}`);
    }

    console.log("✅ Database seeded successfully!");
  } catch (err) {
    console.error("❌ Error seeding database:", err);
  } finally {
    db.close();
  }
}

runSeed();
